apiVersion: v1
kind: Secret
metadata:
  name: portsecret
  namespace: volodymyr-bezpalchuk
type: Opaque
data:
  PORT: MzAzMA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-8
  namespace: volodymyr-bezpalchuk
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: homework-8
  template : 
    metadata:
      labels:
        app: homework-8
    spec:
      containers:
        - name: homework-8
          image: bezpalchukv/ma.devops.bezpalchuk:node-app
          imagePullPolicy: Always  
          envFrom:
            - secretRef:
                name: portsecret              
          resources:
            requests:
              memory: 75M
            limits:
              cpu: 0.1
