---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-configmap
  namespace: sashka-datsenko
data:
  url: http://3.122.159.165:30333
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 2368
      nodePort: 30333
  selector:
    app: ghost-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
  labels:
    app: ghost-app
spec:
  selector:
    matchLabels:
      app: ghost-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghost-app
    spec:
      containers:
        - name: ghost-app
          image: ghost:alpine
          env:
            - name: url
              valueFrom:
                configMapKeyRef:
                  name: ghost-configmap
                  key: url
          ports:
            - containerPort: 2368
          resources: 
            requests:
              memory: 75M
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-1-88