apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-config
data: 
  CONTENT: /var/lib/ghost/content
  url: http://3.122.159.165:30721
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  type: NodePort
  selector:
    app: ghost
  ports:
    - port: 80
      targetPort: 2368
      nodePort: 30721
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: RollingUpdate
  template:
    metadata: 
      labels:
        app: ghost
    spec:
      containers: 
        - name: ghost
          image: ghost
          ports: 
            - containerPort: 2368
          readinessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 50
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 50
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: ghost-config
          volumeMounts:
            - name: ghost-data 
              mountPath: /var/lib/ghost/content      
      volumes: 
        - name: ghost-data
          hostPath: 
            path: /var/lib/ghost/content
      nodeSelector: 
        kubernetes.io/hostname: ip-172-31-1-88
