apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: vladyslav-volkov
  labels:
    app: pod
spec:
  containers:
  - name: app-container
    image: vladvolkov/ma.devops.volkov:latest
    env:
      - name: PORT
        valueFrom:
          secretKeyRef:
            name: app-port
            key: PORT
  restartPolicy: Always
