apiVersion: v1
kind: Secret
metadata:
  name: app-port
  namespace: vladyslav-volkov
type: Opaque
stringData:
  PORT: "8080" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-lesson8
  namespace: vladyslav-volkov
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app-lesson8
  template : 
    metadata:
      labels:
        app: app-lesson8
    spec:
      containers:
        - name: app-lesson8
          image: vladvolkov/ma.devops.volkov:lesson8
          imagePullPolicy: Always  
          envFrom:
            - secretRef:
                name: app-port              
          resources:
            requests:
              memory: 75M
