apiVersion: v1
kind: Secret
metadata:
  name: dockerlogin
  namespace: alexey-boguslavets
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlltOW5kWE5zWVhabGRITTZVMkZ3Y0docGNtVWtNVFU9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xNCAobGludXgpIgoJfQp9
type: kubernetes.io/dockerconfigjson