apiVersion: v1
kind: Pod
metadata:
  name: alex-pod
  namespace: alexey-boguslavets
  labels:
    app: pod
spec:
  containers:
    - name: myapp
      image: boguslavets/ma.devops.boguslavets:1.0
      envFrom:
        - configMapRef:
            name: app
  imagePullSecrets:
  - name: dockerlogin  
  restartPolicy: Never