apiVersion: v1
kind: Secret
metadata:
  name: port
type: Opaque
stringData:
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-deploy
spec:
  selector:
    matchLabels:
      app: alex-deploy
  template:
    metadata:
      labels:
        app: alex-deploy
    spec:
      containers:
        - name: alex-deploy
          imagePullPolicy: Always
          image: boguslavets/ma.devops.boguslavets:1.0
          envFrom:
            - secretRef:
                name: port
          resources: 
            requests:
              memory: 75M
      imagePullSecrets:
        - name: dockerlogin