apiVersion: v1
kind: Secret
metadata:
 name: registrypullsecret
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImNHRjFiR3h2YkRwVFpYSmhaakkxTVRJNE9UQkFVMlZ5WVdZPSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuMTMgKGxpbnV4KSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appjs
  namespace: pavlo-teslenko
spec:
  selector:
    matchLabels:
      app: appjs
  template:
    metadata:
      labels:
        app: appjs
    spec:
      containers:
        - name: appjs
          image: paullol/ma.devops.teslenko.private:1
          envFrom:
            - secretRef:
                name: port
          resources: 
            requests:
              memory: 75M
      imagePullSecrets:
        - name: registrypullsecret 


